// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package task

import (
	"os"
	"sync"
)

var (
	lockServiceMockToOrganizationObject sync.RWMutex
	lockServiceMockToTicketObject       sync.RWMutex
	lockServiceMockToUserObject         sync.RWMutex
	lockServiceMockreadFile             sync.RWMutex
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//     func TestSomethingThatUsesService(t *testing.T) {
//
//         // make and configure a mocked Service
//         mockedService := &ServiceMock{
//             ToOrganizationObjectFunc: func() ([]Organization, error) {
// 	               panic("mock out the ToOrganizationObject method")
//             },
//             ToTicketObjectFunc: func() ([]Ticket, error) {
// 	               panic("mock out the ToTicketObject method")
//             },
//             ToUserObjectFunc: func() ([]User, error) {
// 	               panic("mock out the ToUserObject method")
//             },
//             readFileFunc: func(file *os.File) ([]byte, error) {
// 	               panic("mock out the readFile method")
//             },
//         }
//
//         // use mockedService in code that requires Service
//         // and then make assertions.
//
//     }
type ServiceMock struct {
	// ToOrganizationObjectFunc mocks the ToOrganizationObject method.
	ToOrganizationObjectFunc func() ([]Organization, error)

	// ToTicketObjectFunc mocks the ToTicketObject method.
	ToTicketObjectFunc func() ([]Ticket, error)

	// ToUserObjectFunc mocks the ToUserObject method.
	ToUserObjectFunc func() ([]User, error)

	// readFileFunc mocks the readFile method.
	readFileFunc func(file *os.File) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// ToOrganizationObject holds details about calls to the ToOrganizationObject method.
		ToOrganizationObject []struct {
		}
		// ToTicketObject holds details about calls to the ToTicketObject method.
		ToTicketObject []struct {
		}
		// ToUserObject holds details about calls to the ToUserObject method.
		ToUserObject []struct {
		}
		// readFile holds details about calls to the readFile method.
		readFile []struct {
			// File is the file argument value.
			File *os.File
		}
	}
}

// ToOrganizationObject calls ToOrganizationObjectFunc.
func (mock *ServiceMock) ToOrganizationObject() ([]Organization, error) {
	if mock.ToOrganizationObjectFunc == nil {
		panic("ServiceMock.ToOrganizationObjectFunc: method is nil but Service.ToOrganizationObject was just called")
	}
	callInfo := struct {
	}{}
	lockServiceMockToOrganizationObject.Lock()
	mock.calls.ToOrganizationObject = append(mock.calls.ToOrganizationObject, callInfo)
	lockServiceMockToOrganizationObject.Unlock()
	return mock.ToOrganizationObjectFunc()
}

// ToOrganizationObjectCalls gets all the calls that were made to ToOrganizationObject.
// Check the length with:
//     len(mockedService.ToOrganizationObjectCalls())
func (mock *ServiceMock) ToOrganizationObjectCalls() []struct {
} {
	var calls []struct {
	}
	lockServiceMockToOrganizationObject.RLock()
	calls = mock.calls.ToOrganizationObject
	lockServiceMockToOrganizationObject.RUnlock()
	return calls
}

// ToTicketObject calls ToTicketObjectFunc.
func (mock *ServiceMock) ToTicketObject() ([]Ticket, error) {
	if mock.ToTicketObjectFunc == nil {
		panic("ServiceMock.ToTicketObjectFunc: method is nil but Service.ToTicketObject was just called")
	}
	callInfo := struct {
	}{}
	lockServiceMockToTicketObject.Lock()
	mock.calls.ToTicketObject = append(mock.calls.ToTicketObject, callInfo)
	lockServiceMockToTicketObject.Unlock()
	return mock.ToTicketObjectFunc()
}

// ToTicketObjectCalls gets all the calls that were made to ToTicketObject.
// Check the length with:
//     len(mockedService.ToTicketObjectCalls())
func (mock *ServiceMock) ToTicketObjectCalls() []struct {
} {
	var calls []struct {
	}
	lockServiceMockToTicketObject.RLock()
	calls = mock.calls.ToTicketObject
	lockServiceMockToTicketObject.RUnlock()
	return calls
}

// ToUserObject calls ToUserObjectFunc.
func (mock *ServiceMock) ToUserObject() ([]User, error) {
	if mock.ToUserObjectFunc == nil {
		panic("ServiceMock.ToUserObjectFunc: method is nil but Service.ToUserObject was just called")
	}
	callInfo := struct {
	}{}
	lockServiceMockToUserObject.Lock()
	mock.calls.ToUserObject = append(mock.calls.ToUserObject, callInfo)
	lockServiceMockToUserObject.Unlock()
	return mock.ToUserObjectFunc()
}

// ToUserObjectCalls gets all the calls that were made to ToUserObject.
// Check the length with:
//     len(mockedService.ToUserObjectCalls())
func (mock *ServiceMock) ToUserObjectCalls() []struct {
} {
	var calls []struct {
	}
	lockServiceMockToUserObject.RLock()
	calls = mock.calls.ToUserObject
	lockServiceMockToUserObject.RUnlock()
	return calls
}

// readFile calls readFileFunc.
func (mock *ServiceMock) readFile(file *os.File) ([]byte, error) {
	if mock.readFileFunc == nil {
		panic("ServiceMock.readFileFunc: method is nil but Service.readFile was just called")
	}
	callInfo := struct {
		File *os.File
	}{
		File: file,
	}
	lockServiceMockreadFile.Lock()
	mock.calls.readFile = append(mock.calls.readFile, callInfo)
	lockServiceMockreadFile.Unlock()
	return mock.readFileFunc(file)
}

// readFileCalls gets all the calls that were made to readFile.
// Check the length with:
//     len(mockedService.readFileCalls())
func (mock *ServiceMock) readFileCalls() []struct {
	File *os.File
} {
	var calls []struct {
		File *os.File
	}
	lockServiceMockreadFile.RLock()
	calls = mock.calls.readFile
	lockServiceMockreadFile.RUnlock()
	return calls
}
